#!/bin/sh
#
# Auto connect bluetooth controllers
#

systemsetting="python /usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"

case "$1" in
  start)
        enabled="`$systemsetting  -command load -key controllers.bluetooth.enabled`"
        if [ "$enabled" == "1" ];then
		start-stop-daemon -S -q -m -p /var/run/bluetoothd.pid  --exec /usr/libexec/bluetooth/bluetoothd &	
		( /recalbox/scripts/bluetoothcontrollers.sh && \
                  start-stop-daemon -S -q -m -p /var/run/btDaemon.pid  --exec /recalbox/scripts/bluetooth/btDaemon > /dev/null 2>&1 ) &
        fi
        ;;
  stop)
	start-stop-daemon -K -q -p /var/run/btDaemon.pid
	start-stop-daemon -K -q -p /var/run/bluetoothd.pid
	;;
  restart|reload)
        "$0" stop
        "$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


